CREATE TABLE USERINFO 
(
  "UID" NUMBER NOT NULL 
, BALANCE NUMBER 
, CONSTRAINT PK_UID PRIMARY KEY 
  (
    "UID" 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

COMMENT ON COLUMN USERINFO."UID" IS 'SID';

COMMENT ON COLUMN USERINFO.BALANCE IS 'æl√B';
