CREATE TABLE BOOK 
(
  BID NUMBER NOT NULL 
, BNAME NVARCHAR2(50) 
, PRICE NUMBER 
, CONSTRAINT PK_BID PRIMARY KEY 
  (
    BID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);


COMMENT ON COLUMN BOOK.BID IS 'SID';

COMMENT ON COLUMN BOOK.BNAME IS '書名';

COMMENT ON COLUMN BOOK.PRICE IS '價格';